name: medications
description: App para busca de medicamentos

version: 1.0.0+1
environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  modal_progress_hud: ^0.1.3
  json_annotation: ^3.0.0
  dio: ^3.0.7
  cupertino_icons: ^0.1.2
  mobx: ^0.4.0+1
  flutter_mobx: ^0.3.6
  provider: ^4.3.1
  flutter_pagination_helper: ^1.0.0+5
  logger: ^0.9.2
  flutter_launcher_icons: ^0.7.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.7.3
  json_serializable: ^3.3.0
  mobx_codegen: 0.4.0+1

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"
